// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB75hhfvhLaKZ_Etzc4m5nUtUPQwKuFAA',
    appId: '1:636272163985:web:48d123413973c50a37d330',
    messagingSenderId: '636272163985',
    projectId: 'musicapp-31ca0',
    authDomain: 'musicapp-31ca0.firebaseapp.com',
    storageBucket: 'musicapp-31ca0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UPTb-rvLrwLpDfXnMJHKnyvh9DjmlKg',
    appId: '1:636272163985:android:d38dbdde38fb4c0e37d330',
    messagingSenderId: '636272163985',
    projectId: 'musicapp-31ca0',
    storageBucket: 'musicapp-31ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzp2wAk_neMcghb6NHexswPVA2Mlssht0',
    appId: '1:636272163985:ios:0383c4e7abb5f3b837d330',
    messagingSenderId: '636272163985',
    projectId: 'musicapp-31ca0',
    storageBucket: 'musicapp-31ca0.appspot.com',
    iosClientId:
        '636272163985-lhmjc4aprh8qecvapndonvtss0j8d9c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzp2wAk_neMcghb6NHexswPVA2Mlssht0',
    appId: '1:636272163985:ios:0383c4e7abb5f3b837d330',
    messagingSenderId: '636272163985',
    projectId: 'musicapp-31ca0',
    storageBucket: 'musicapp-31ca0.appspot.com',
    iosClientId:
        '636272163985-lhmjc4aprh8qecvapndonvtss0j8d9c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
